### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by badamakashprasad** [Arkoprobho-Pal/Sr_Project#1]
how can we contribute when we don't know cpp. I suggest to use python for this. It would be easier for this type of projects.

**Comment by Arkoprobho-Pal** [comment]
Sorry, my friend, Python is known to You only, But My version of Cpp is known to all because it's very similar to C. I understand that in Python, the code would be lesser but we have to learn it first. Try to deal with, what we have, then we'll try to move to another language
